amsgrad: false
arch: AUNet_R16
batch_size: 4
cuda_num: 1
dataset: radiography
deep_supervision: false
dice_loss: true
early_stopping: -1
epochs: 200
factor: 0.1
gamma: 0.1
img_ext: .png
input_channels: 3
input_h: 512
input_w: 512
label_name: union
loss: CELoss
lr: 0.0001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: radiography_newdataset31ordibehesht_512_4_dice_AUNet_R16__05062021_0434
nesterov: false
num_classes: 4
num_workers: 4
optimizer: Adam
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
